language: java
before_install:
- chmod +x gradlew
jdk:
- oraclejdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.gradle"
script:
- "./gradlew clean build"
notifications:
  slack:
    rooms:
      secure: LaxYcn5dEwLgVUXt0GwuKBYFu0GdXfgIorpcKagXeB1aayYePHcY7oRXDVBKQbVnCun/G9cdVLOccVVWL6Zec/K7Bdwa0jnLgEPzpRUrGP3g9i3u7UTtmfjymLP0pLOY6gFfSNLSVELNO104wwUvbycuuE0x9yIKcXkSbFzJ4vPMqr5y1DrYQxgMGcPlt5+lLGCtZjYHbX5RyBjaiA53d3HEGCD6CkqRPIituVmqn3FkPXqJqONErLWtE/lvONSj6p2scl6sZIEetLNOxaJZwwdhhWfp00u1t+7ns1ZdNgwBrEIksNtIpq5yVixW0Hm+j7xv/+J/M8f+tu/P48JPv3j9Ho5viKFbHJJOEJNPj72a+Z/0wA+UvS/gkvdvOHY80oU8CIHZPMrpL5vIHZN2qgVPZ0UNsxa9iHLaZewXVuoiyj6VWGIL+7bGsFXApxg7VgzZxNg/uo3qnpMR1hAvfjP8UTNxYXEK0vMOodNmQYPvjry9y8+oUbkNJJ7CSIxvWiVKW2UFPUMAYJeHKfC33CLLIracvhgjMT6badHlvg3AHXAMUPHFvAdyx7RBkmiVkY9VHxsq5K2NqG/HaeafYAI4ssLs8+JvF19ZRQrzzcoGZvJP3DxaXIW4NZRE3Xt94qTfnSsmMFAlh4QHHACb+iNPf/OlgBlPRpIByALZiYk=
deploy:
  provider: heroku
  api_key:
    secure: JpwTwdHF/9Hzjkqv2/pvBQZHS2zbflIs0R5Sk1CFyX0qoXzDYaFtl3iTLqRESjw7tAmDl8aEzWkM1Pr5GFRqZJICJANFT1sUbWHlOlFxRF8FmOhvTrx8XU4b4R+hzo7CYkWUtOBgKei1LTkCwifxz0HZh+vpnv+xos/k4ktFTsArGqsNYRMX1CNa5CQlsrPPGDxgm5ZAQ7i1RhUau5BFfYu19ihg70LHvgU3eAJNWdBGMRXvYAx1PAYJ6opqSqgbPwoSOkwNDToldZrV3yF17KPWO2kC/HzPKIIhUYD3Qm6Mj6HilCX46nWPmaUCoM2GcvkatADjTsHrcBPgwQ3Qmddr3Ou3J7Cy5sRrG7CfSWqWJjCsRb20wwMT0YVRd0pRdD5N1ECYJmB3VBmH2WeQ/SFHDSC8U7219X7xFaI7Ll+1nHkeiqEGc3rPK42MoAE8QEc0DZWlw/2TpFFzZcRktj7ec35I3HXxa0m2+sEVYaEFd8t6Wl2CDuViPODkjXIIUNzLaIX+0YZO3Tuh8g94J0zEDz9pmlISTZVQaf50DQMNBnwbLFutk84Icx/RExhVUwqN/k5SuzbE32EUwi1zqd5/LjQ7l0zdhiPIYeq4T+jH6urYM2GhaU/rH27mfHY6YET1xNXsv+GiKJ7wcbFVx/aRjvjUjygLvmYOer5grQs=
  app: exercisetest
