language: java
before_install:
 - chmod +x gradlew
jdk:
 - oraclejdk8
branches:
  only:
   - master
cache:
  directories:
   - "$HOME/.gradle"
script:
 - "./gradlew clean build"
notifications:
 slack: cozyan:RJNQYM12vhZGjcfGaOBo6qo6